# Generated by Django 5.1.2 on 2024-10-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_questions_id_alter_questions_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="label",
            field=models.BooleanField(default=False),
        ),
    ]
